#snowflake id
#e.g. 2025-06-01T00:00:00Z
snowflake.epoch=${snowflake.epoch}
#
snowflake.datacenter.id=${snowflake.datacenter.id}
snowflake.worker.id=${snowflake.worker.id}
#bit number
snowflake.timestamp.bits=${snowflake.timestamp.bits}
snowflake.datacenter.bits=${snowflake.datacenter.bits}
snowflake.worker.bits=${snowflake.worker.bits}
snowflake.sequence.bits=${snowflake.sequence.bits}
# worker id generation:[zk,ip]
snowflake.worker.generation=${snowflake.worker.generation}
#worker's ip env name
snowflake.worker.env.ip=${snowflake.worker.env.ip}
#zk
snowflake.zk.id=${snowflake.zk.id}
snowflake.zk.worker.path=${snowflake.zk.worker.path}


