-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 01:41:52 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jframe_pay
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jframe_pay` ;

-- -----------------------------------------------------
-- Schema jframe_pay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jframe_pay` DEFAULT CHARACTER SET utf8mb4 ;
USE `jframe_pay` ;

-- -----------------------------------------------------
-- Table `jframe_pay`.`usr_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jframe_pay`.`usr_account` ;

CREATE TABLE IF NOT EXISTS `jframe_pay`.`usr_account` (
  `account` VARCHAR(30) NOT NULL COMMENT '',
  `mobile` VARCHAR(20) NOT NULL COMMENT '',
  `name` VARCHAR(20) NOT NULL COMMENT '',
  `type` TINYINT(8) NOT NULL COMMENT '',
  `passwd` VARCHAR(45) NULL COMMENT '',
  `sex` TINYINT(1) NULL DEFAULT 2 COMMENT '',
  `realname` VARCHAR(20) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `amount` BIGINT NULL DEFAULT 0 COMMENT '',
  `create_time` TIMESTAMP NULL COMMENT '',
  `modify_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`account`)  COMMENT '')
ENGINE = InnoDB;

CREATE UNIQUE INDEX `mobile_UNIQUE` ON `jframe_pay`.`usr_account` (`mobile` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `jframe_pay`.`order_alipay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jframe_pay`.`order_alipay` ;

CREATE TABLE IF NOT EXISTS `jframe_pay`.`order_alipay` (
  `pay_no` VARCHAR(25) NOT NULL COMMENT '',
  `pay_group` VARCHAR(45) NULL COMMENT '',
  `trans_type` INT NOT NULL COMMENT '',
  `pay_amount` BIGINT NOT NULL COMMENT '',
  `pay_currency` INT NOT NULL COMMENT '',
  `pay_desc` VARCHAR(255) NULL COMMENT '',
  `pay_timeout` TIMESTAMP NULL COMMENT '',
  `back_url` VARCHAR(255) NULL COMMENT '',
  `account` VARCHAR(30) NOT NULL COMMENT '',
  `order_no` VARCHAR(45) NOT NULL COMMENT '',
  `order_status` INT NOT NULL COMMENT '',
  `order_finish_time` TIMESTAMP NULL COMMENT '',
  `order_create_time` TIMESTAMP NULL COMMENT '',
  `notify_time` TIMESTAMP NULL COMMENT '',
  `notify_type` VARCHAR(32) NULL COMMENT '',
  `notify_id` VARCHAR(255) NULL COMMENT '',
  `subject` VARCHAR(128) NULL COMMENT '',
  `trade_status` VARCHAR(20) NULL COMMENT '',
  `seller_id` VARCHAR(30) NULL COMMENT '',
  `seller_email` VARCHAR(100) NULL COMMENT '',
  `buyer_id` VARCHAR(30) NULL COMMENT '',
  `buyer_email` VARCHAR(100) NULL COMMENT '',
  `create_time` TIMESTAMP NULL COMMENT '',
  `modify_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`pay_no`)  COMMENT '')
ENGINE = InnoDB;

CREATE INDEX `index_paygrp` ON `jframe_pay`.`order_alipay` (`pay_group` ASC)  COMMENT '';

CREATE UNIQUE INDEX `order_no_UNIQUE` ON `jframe_pay`.`order_alipay` (`order_no` ASC)  COMMENT '';

CREATE INDEX `index_account` ON `jframe_pay`.`order_alipay` (`account` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `jframe_pay`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jframe_pay`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `jframe_pay`.`order_detail` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `desc` VARCHAR(255) NULL COMMENT '',
  `amount` BIGINT NULL DEFAULT 0 COMMENT '',
  `pay_no` VARCHAR(25) NOT NULL COMMENT '',
  `pay_group` VARCHAR(45) NULL COMMENT '',
  `trans_type` INT NOT NULL COMMENT '',
  `account_from` VARCHAR(30) NULL COMMENT '',
  `account_to` VARCHAR(30) NULL COMMENT '',
  `income` BIGINT NULL DEFAULT 0 COMMENT '',
  `create_time` TIMESTAMP NULL COMMENT '',
  `modify_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '')
ENGINE = InnoDB;

CREATE INDEX `index_id` ON `jframe_pay`.`order_detail` (`id` ASC)  COMMENT '';

CREATE INDEX `index_pay` ON `jframe_pay`.`order_detail` (`pay_group` ASC, `pay_no` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `jframe_pay`.`order_wx`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jframe_pay`.`order_wx` ;

CREATE TABLE IF NOT EXISTS `jframe_pay`.`order_wx` (
  `pay_no` VARCHAR(25) NOT NULL COMMENT '',
  `pay_group` VARCHAR(45) NULL COMMENT '',
  `trans_type` INT NOT NULL COMMENT '',
  `pay_amount` BIGINT NOT NULL COMMENT '',
  `pay_currency` INT NOT NULL COMMENT '',
  `pay_desc` VARCHAR(255) NULL COMMENT '',
  `pay_timeout` TIMESTAMP NULL COMMENT '',
  `back_url` VARCHAR(255) NULL COMMENT '',
  `account` VARCHAR(30) NOT NULL COMMENT '',
  `order_no` VARCHAR(45) NOT NULL COMMENT '',
  `order_status` INT NOT NULL COMMENT '',
  `order_finish_time` TIMESTAMP NULL COMMENT '',
  `order_create_time` TIMESTAMP NULL COMMENT '',
  `resp_code` VARCHAR(4) NULL COMMENT '',
  `resp_desc` VARCHAR(255) NULL COMMENT '',
  `transaction_id` VARCHAR(28) NULL COMMENT '',
  `out_refund_no` VARCHAR(32) NULL COMMENT '',
  `refund_fee` INT(11) NULL COMMENT '',
  `refund_type` INT(11) NULL COMMENT '',
  `refund_id` VARCHAR(28) NULL COMMENT '',
  `refund_channel` INT(11) NULL COMMENT '',
  `refund_status` INT(11) NULL COMMENT '',
  `recv_user_id` VARCHAR(64) NULL COMMENT '',
  `recv_user_name` VARCHAR(32) NULL COMMENT '',
  `trade_mode` INT(11) NULL COMMENT '',
  `pay_info` VARCHAR(64) NULL COMMENT '',
  `bank_type` VARCHAR(16) NULL COMMENT '',
  `bank_billno` VARCHAR(32) NULL COMMENT '',
  `notify_id` VARCHAR(128) NULL COMMENT '',
  `time_end` VARCHAR(14) NULL COMMENT '',
  `transport_fee` INT(11) NULL COMMENT '',
  `product_fee` INT(11) NULL COMMENT '',
  `discount` INT(11) NULL COMMENT '',
  `buyer_alias` VARCHAR(64) NULL COMMENT '',
  `create_time` TIMESTAMP NULL COMMENT '',
  `modify_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`pay_no`)  COMMENT '')
ENGINE = InnoDB;

CREATE INDEX `index_paygrp` ON `jframe_pay`.`order_wx` (`pay_group` ASC)  COMMENT '';

CREATE UNIQUE INDEX `order_no_UNIQUE` ON `jframe_pay`.`order_wx` (`order_no` ASC)  COMMENT '';

CREATE INDEX `index_account` ON `jframe_pay`.`order_wx` (`account` ASC)  COMMENT '';

SET SQL_MODE = '';
GRANT USAGE ON *.* TO pay;
 DROP USER pay;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'pay' IDENTIFIED BY 'pay123';

GRANT ALL ON `jframe_pay`.* TO 'pay';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
